config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-inverse">
      <a class="navbar-brand" href="<%= pages_one_path %>">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a  class="nav-item nav-link" href="<%= pages_one_path %>">One</a><span class="sr-only">(current)</span></a>
          <a  class="nav-item nav-link" href="<%= pages_two_path %>">Two</a>
          <a  class="nav-item nav-link" href="<%= pages_three_path %>">Three</a>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Pages#one</h1>
<h1>Gilibeth Stefani Vega</h1>
<p>Find me in app/views/pages/one.html.erb</p>

app/views/pages/three.html.erb
<h1>Pages#three</h1>
<h2> Lorem ipsum dolor <h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in neque ut quam sollicitudin molestie quis ac justo. 
Pellentesque accumsan, urna a malesuada efficitur, diam tellus egestas tortor, nec semper mauris libero posuere ex. 
Duis lacus diam, imperdiet id luctus eget, ornare non felis. Curabitur gravida, sapien non elementum consectetur, massa lacus semper tortor, facilisis sodales lectus ex in eros. 
Morbi et nulla ac ex placerat molestie. Nam fringilla nunc vitae nisl rhoncus mattis. Nulla ac iaculis dolor. In mattis elit et neque faucibus, 
id tristique eros lacinia. Integer feugiat congue magna quis elementum. Vestibulum sed neque id leo facilisis interdum et in metus. 
Maecenas id tempor lectus. Ut mi dolor, consequat a tempor semper, scelerisque sit amet lectus.</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>

<%= image_tag 'rake_routes.PNG' %>

<p>Find me in app/views/pages/two.html.erb</p>